version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "20:00"
  open-pull-requests-limit: 10
  assignees:
  - kanghyojun
  ignore:
  - dependency-name: typescript
    versions:
    - 4.2.2
  - dependency-name: "@types/koa"
    versions:
    - 2.13.0
  - dependency-name: eslint
    versions:
    - 7.21.0
